// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package err

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERR_INVALID_PARAM-3000]
	_ = x[ERR_INVALID_EMAIL-3001]
}

const _ErrorCode_name = "ERR_INVALID_PARAMERR_INVALID_EMAIL"

var _ErrorCode_index = [...]uint8{0, 17, 34}

func (i ErrorCode) String() string {
	i -= 3000
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+3000), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
